### ISSUE TITLE
generics

### ISSUE THREAD

**Issue by amirhnajafiz** [bregman-arie/go-exercises#3]
Hi there dear @bregman-arie, I saw your repository and I was hoping that you could let me add Golang ```generics```
example and exercise.

Here is an example of what I want to add to this repository.

- [github.com/amirhnajafiz/go-generics](https://github.com/amirhnajafiz/go-generics)

**Comment by bregman-arie** [comment]
Sure, any contributions are more than welcome :)

**Comment by amirhnajafiz** [comment]
Thank you dear @bregman-arie
